### ISSUE TITLE
Fix DVC folder permissions, add correct folders to DVC

### ISSUE THREAD

**Issue by andste97** [adoprox/Group60_mlops#2]
Seems like folders added to DVC and permissions to access the folder DVC uploads to are broken.

Please make everyone access the Gdrive folder 1hTJ0wghBp-5BabYJq3Cg9kUj2rdoEhIe

**Comment by adoprox** [comment]
I've updated the access rights, can someone try and lemme know if it works.

**Comment by andste97** [comment]
Access to the folder is working now, thank you! There is still one issue though: the data gets put into the wrong folder, <project_root>/ml_project_data. Data should be put in the folder <project_root>/data

**Comment by adoprox** [comment]
Read the last few lines in README inside the Group60 folder
I've given the instructions on how to change that.
